name: Run Playwright Tests with Allure

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm run test
 
      - name: Install Allure CLI
        run: |
          npm install -g allure-commandline --save-dev
      
      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      - name: Upload Allure Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
            name: screenshots
            path: '**/*.png'

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: '**/*.trace.zip'
      
      - name: 📤 Deploy Playwright Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          publish_branch: gh-pages
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          
          
